### ISSUE TITLE
Хабраэфект положил сервера вконтакте?

### ISSUE THREAD

**Issue by krll-k** [romkagolovadvayha/getmembersVKAPI#1]
<a class="dev_platform_info" href="/dev/health">
  <div class="dev_info_status_header">Статус платформы</div>
  <div class="dev_info_ping clear_fix">
    <div class="dev_info_svg fl_l"><svg width="53" height="53">
  <path fill="none" stroke="rgba(236, 176, 47, 0.4)" stroke-width="3" d="M 26.5 3 A 23.5 23.5 0 1 0 26.500147654855 3.0000000004639"></path>
  <path fill="none" stroke="rgba(236, 176, 47, 1)" stroke-width="3" d="M 26.5 12.4 L 26.5 26.5 L 15.575126290813 30.825463494045"></path>
</svg></div>
    <div class="dev_info_label fl_l">
      <div class="dev_info_status" style="color: rgb(236, 176, 47);">
  <span class="dev_info_status_val">138</span>
  <span class="dev_info_status_label">ms</span>
</div>
      <div class="dev_info_status_text">Среднее время ответа</div>
    </div>
  </div>
  <div class="dev_info_uptime clear_fix">
    <div class="dev_info_svg fl_l"><svg width="53" height="53">
  <path fill="none" stroke="rgba(236, 176, 47, 0.2)" stroke-width="3" d="M 26.5 3 A 23.5 23.5 0 1 0 26.500147654855 3.0000000004639"></path>
  <path fill="none" stroke="rgba(236, 176, 47, 1)" stroke-width="3" d="M 16.069281570612 5.4417447767667 A 23.5 23.5 0 1 0 26.5 3"></path>
</svg></div>
    <div class="dev_info_label fl_l">
      <div class="dev_info_status" style="color: rgb(236, 176, 47);">
  <span class="dev_info_status_val">92.68</span>
  <span class="dev_info_status_label">%</span>
</div>
      <div class="dev_info_status_text">Uptime</div>
    </div>
  </div>
</a>

**Comment by romkagolovadvayha** [comment]
вполне возможно, но я не думаю что это так. В статистике приложения не так много запросов к серверу vk, чтобы он лег.
